{
  "channels": [
    {
      "id": "daily-verse",
      "name": "Daily Verse",
      "description": "A Bible verse for each day of the year",
      "type": "evergreen",
      "category": "scripture",
      "language": "en",
      "region": null,
      "tradition": "ecumenical",
      "icon": "📖",
      "color": "#667eea",
      "author": "SANGOCAST Team",
      "version": "1.0",
      "requiresSubscription": false,
      "isPremium": false,
      "updateFrequency": "daily",
      "contentCount": 365,
      "content": [
        {
          "date": "2026-02-20",
          "verse": "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.",
          "reference": "John 3:16",
          "translation": "NIV"
        }
      ],
      "defaultContent": {
        "verse": "Trust in the Lord with all your heart and lean not on your own understanding.",
        "reference": "Proverbs 3:5",
        "translation": "NIV"
      }
    },
    {
      "id": "prayer-times",
      "name": "Daily Prayer Times",
      "description": "Traditional prayer times and liturgies",
      "type": "evergreen",
      "category": "prayer",
      "language": "en",
      "region": null,
      "tradition": "ecumenical",
      "icon": "🙏",
      "color": "#10b981",
      "requiresSubscription": false,
      "isPremium": false,
      "updateFrequency": "daily",
      "content": []
    },
    {
      "id": "rosary-meditations",
      "name": "Rosary Meditations",
      "description": "Daily meditations for the Holy Rosary",
      "type": "evergreen",
      "category": "devotional",
      "language": "en",
      "region": null,
      "tradition": "catholic",
      "icon": "📿",
      "color": "#8b5cf6",
      "requiresSubscription": false,
      "isPremium": false,
      "updateFrequency": "daily",
      "content": []
    },
    {
      "id": "orthodox-calendar",
      "name": "Orthodox Liturgical Calendar",
      "description": "Feast days and readings from the Orthodox tradition",
      "type": "evergreen",
      "category": "worship",
      "language": "en",
      "region": null,
      "tradition": "orthodox",
      "icon": "☦️",
      "color": "#f59e0b",
      "requiresSubscription": false,
      "isPremium": false,
      "updateFrequency": "daily",
      "content": []
    },
    {
      "id": "live-worship",
      "name": "Live Worship Services",
      "description": "Stream live worship services from around the world",
      "type": "live",
      "category": "worship",
      "language": "en",
      "region": null,
      "tradition": "ecumenical",
      "icon": "🎤",
      "color": "#ef4444",
      "requiresSubscription": true,
      "isPremium": false,
      "updateFrequency": "live",
      "content": []
    },
    {
      "id": "christian-news",
      "name": "Christian News Feed",
      "description": "Latest news from Christian media outlets",
      "type": "live",
      "category": "news",
      "language": "en",
      "region": null,
      "tradition": "ecumenical",
      "icon": "📰",
      "color": "#3b82f6",
      "requiresSubscription": false,
      "isPremium": false,
      "updateFrequency": "hourly",
      "content": []
    },
    {
      "id": "easter-2026",
      "name": "Easter 2026 Devotional",
      "description": "40-day Lenten devotional leading to Easter Sunday",
      "type": "event",
      "category": "event",
      "language": "en",
      "region": null,
      "tradition": "ecumenical",
      "icon": "🌅",
      "color": "#fbbf24",
      "requiresSubscription": false,
      "isPremium": false,
      "eventDate": "2026-02-18",
      "eventEndDate": "2026-04-05",
      "downloadSize": 2500000,
      "downloadUrl": "/api/events/easter-2026/download",
      "updateFrequency": "event",
      "contentCount": 40,
      "content": []
    },
    {
      "id": "christmas-advent-2026",
      "name": "Advent Calendar 2026",
      "description": "Daily devotions for the Advent season",
      "type": "event",
      "category": "event",
      "language": "en",
      "region": null,
      "tradition": "ecumenical",
      "icon": "🎄",
      "color": "#dc2626",
      "requiresSubscription": false,
      "isPremium": false,
      "eventDate": "2026-11-29",
      "eventEndDate": "2026-12-25",
      "downloadSize": 1800000,
      "downloadUrl": "/api/events/advent-2026/download",
      "updateFrequency": "event",
      "contentCount": 25,
      "content": []
    },
    {
      "id": "sermon-series-faith",
      "name": "Faith Foundations Series",
      "description": "12-week sermon series on the basics of Christian faith",
      "type": "event",
      "category": "teaching",
      "language": "en",
      "region": null,
      "tradition": "protestant",
      "icon": "🎓",
      "color": "#059669",
      "requiresSubscription": false,
      "isPremium": true,
      "eventDate": "2026-01-01",
      "eventEndDate": "2026-03-31",
      "downloadSize": 52000000,
      "downloadUrl": "/api/events/faith-series/download",
      "updateFrequency": "event",
      "contentCount": 12,
      "content": []
    },
    {
      "id": "psalms-devotional",
      "name": "Psalms Daily Devotional",
      "description": "Journey through all 150 Psalms with daily reflections",
      "type": "evergreen",
      "category": "devotional",
      "language": "en",
      "region": null,
      "tradition": "ecumenical",
      "icon": "🎵",
      "color": "#7c3aed",
      "requiresSubscription": false,
      "isPremium": false,
      "updateFrequency": "daily",
      "contentCount": 150,
      "content": []
    }
  ]
}
